---
- name: Create frontend network
  community.docker.docker_network:
    name: frontend
    driver: overlay
    attachable: true

- name: Create backend network
  community.docker.docker_network:
    name: backend
    driver: overlay
    attachable: true

