---
- name: Create Wazuh admin password secret
  community.docker.docker_secret:
    name: wazuh_admin_password
    data: "{{ wazuh_admin_password }}"
    state: present
  when: wazuh_admin_password is defined
