---
- hosts: swarm_managers
  become: yes
  vars:
    wazuh_admin_password: "{{ lookup('env', 'WAZUH_ADMIN_PASSWORD') }}"
    traefik_acme_email: "{{ lookup('env', 'TRAEFIK_ACME_EMAIL') }}"
  roles:
    - swarm
    - networks
    - secrets
    - stack

- name: Wait for services to be ready
  hosts: swarm_managers
  tasks:
    - name: Wait for Wazuh dashboard
      uri:
        url: "https://{{ domain_name }}"
        method: GET
        validate_certs: false
      register: result
      until: result.status == 200
      retries: 30
      delay: 10
