api:
  dashboard: true
  insecure: true  # Remove in production

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${TRAEFIK_ACME_EMAIL}
      storage: /certificates/acme.json
      httpChallenge:
        entryPoint: web

# Redirect HTTP to HTTPS
http:
  redirections:
    entryPoint:
      to: websecure
      scheme: https
